dist: trusty

addons:
  chrome: stable

before_install:
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &

language: node_js

node_js:
  - '7'

after_script: 'cat ./coverage/HeadlessChrome*/lcov.info | ./node_modules/coveralls/bin/coveralls.js'
